// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using planetnineserver.Data;

#nullable disable

namespace planetnineserver.Migrations
{
    [DbContext(typeof(planetnineservercontext))]
    [Migration("20230421052032_Planets")]
    partial class Planets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("planetnineserver.Models.ArtificialIntelligence", b =>
                {
                    b.Property<int>("ArtificialIntelligenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtificialIntelligenceId");

                    b.HasIndex("UserId");

                    b.ToTable("ArtificialIntelligences");
                });

            modelBuilder.Entity("planetnineserver.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtificialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtificialIntelligenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.HasIndex("ArtificialIntelligenceId");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("planetnineserver.Models.ChatComment", b =>
                {
                    b.Property<int>("ChatCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtificialIntelligenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatCommentId");

                    b.HasIndex("ArtificialIntelligenceId");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatComments");
                });

            modelBuilder.Entity("planetnineserver.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentId");

                    b.HasIndex("ChatId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("planetnineserver.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatCommentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MessageCommentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MoonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FavoriteId");

                    b.HasIndex("ChatCommentId");

                    b.HasIndex("ChatId");

                    b.HasIndex("CommentId");

                    b.HasIndex("MessageCommentId");

                    b.HasIndex("MoonId");

                    b.HasIndex("PlanetId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("planetnineserver.Models.Follower", b =>
                {
                    b.Property<int>("FollowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowerUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowerId");

                    b.HasIndex("UserId");

                    b.ToTable("Follower");
                });

            modelBuilder.Entity("planetnineserver.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("planetnineserver.Models.MessageComment", b =>
                {
                    b.Property<int>("MessageCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageCommentId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageComment");
                });

            modelBuilder.Entity("planetnineserver.Models.Moon", b =>
                {
                    b.Property<int>("MoonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aphelion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonMass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perihelion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoonId");

                    b.HasIndex("PlanetId");

                    b.HasIndex("UserId");

                    b.ToTable("Moon");
                });

            modelBuilder.Entity("planetnineserver.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aphelion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Perihelion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetMass")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanetId");

                    b.HasIndex("UserId");

                    b.ToTable("Planet");

                    b.HasData(
                        new
                        {
                            PlanetId = 2,
                            Aphelion = "69816900",
                            Gravity = "3.7",
                            ImageLink = "https://solarsystem.nasa.gov/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0VRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b43e79a5b43d2063c4866ccff66bede5faff17b8/mercury_th.jpg",
                            Perihelion = "46001200",
                            PlanetMass = "3.30114",
                            PlanetName = "Mercury",
                            Temperature = "5.4291",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 3,
                            Aphelion = "108939000",
                            Gravity = "8.87",
                            ImageLink = "https://solarsystem.nasa.gov/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajl5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1771be6bd46710c30aa93cd6c3ababe23ad52681/480x320_venus.png?disposition=inline",
                            Perihelion = "107477000",
                            PlanetMass = "4.86747",
                            PlanetName = "Venus",
                            Temperature = "5.243",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 4,
                            Aphelion = "152100000",
                            Gravity = "9.8",
                            ImageLink = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Earth_from_Space.jpg/2048px-Earth_from_Space.jpg",
                            Perihelion = "147095000",
                            PlanetMass = "5.97237",
                            PlanetName = "Earth",
                            Temperature = "5.5136",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 5,
                            Aphelion = "249200000",
                            Gravity = "3.7",
                            ImageLink = "https://solarsystem.nasa.gov/system/stellar_items/image_files/6_mars.jpg",
                            Perihelion = "206700000",
                            PlanetMass = "3.71",
                            PlanetName = "Mars",
                            Temperature = "3.9341",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 6,
                            Aphelion = "816620000",
                            Gravity = "24.79",
                            ImageLink = "https://solarsystem.nasa.gov/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGxyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--229ba26c079b7122001319d5dcffec49c8d4e0cb/STSCI-H-p1936a-f-640.jpg?disposition=attachment",
                            Perihelion = "740379835",
                            PlanetMass = "1.89819",
                            PlanetName = "Jupiter",
                            Temperature = "1.3262",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 7,
                            Aphelion = "1503509229",
                            Gravity = "10.44",
                            ImageLink = "https://solarsystem.nasa.gov/system/stellar_items/image_files/38_saturn_1600x900.jpg",
                            Perihelion = "1349823615",
                            PlanetMass = "5.68336",
                            PlanetName = "Saturn",
                            Temperature = "0.6871",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 8,
                            Aphelion = "3006318143",
                            Gravity = "8.87",
                            ImageLink = "https://images.english.elpais.com/resizer/BH_KvY_lAzwSrpp8v7D55nGax8A=/1960x1470/filters:focal(2464x2210:2474x2220)/cloudfront-eu-central-1.images.arcpublishing.com/prisa/WQ773ELGFRDOHJ46MOLRXKJ7AY.jpg",
                            Perihelion = "2734998229",
                            PlanetMass = "8.68127",
                            PlanetName = "Uranus",
                            Temperature = "1.27",
                            Type = "planet",
                            UserId = 1
                        },
                        new
                        {
                            PlanetId = 9,
                            Aphelion = "4537039826",
                            Gravity = "11.15",
                            ImageLink = "https://solarsystem.nasa.gov/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkp5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb7cb2868fd8b4892788893961c20975baffeb52/neptune_480x320.jpg?disposition=inline",
                            Perihelion = "4459753056",
                            PlanetMass = "1.02413",
                            PlanetName = "Neptune",
                            Temperature = "1.638",
                            Type = "planet",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("planetnineserver.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("planetnineserver.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("planetnineserver.Models.ArtificialIntelligence", b =>
                {
                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Chat", b =>
                {
                    b.HasOne("planetnineserver.Models.ArtificialIntelligence", "ArtificialIntelligence")
                        .WithMany("Chats")
                        .HasForeignKey("ArtificialIntelligenceId");

                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtificialIntelligence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.ChatComment", b =>
                {
                    b.HasOne("planetnineserver.Models.ArtificialIntelligence", null)
                        .WithMany("ChatComments")
                        .HasForeignKey("ArtificialIntelligenceId");

                    b.HasOne("planetnineserver.Models.Chat", "Chat")
                        .WithMany("ChatComments")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("planetnineserver.Models.Comment", b =>
                {
                    b.HasOne("planetnineserver.Models.Chat", null)
                        .WithMany("Comments")
                        .HasForeignKey("ChatId");

                    b.HasOne("planetnineserver.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Favorite", b =>
                {
                    b.HasOne("planetnineserver.Models.ChatComment", null)
                        .WithMany("Favorites")
                        .HasForeignKey("ChatCommentId");

                    b.HasOne("planetnineserver.Models.Chat", null)
                        .WithMany("Favorites")
                        .HasForeignKey("ChatId");

                    b.HasOne("planetnineserver.Models.Comment", null)
                        .WithMany("Favorites")
                        .HasForeignKey("CommentId");

                    b.HasOne("planetnineserver.Models.MessageComment", null)
                        .WithMany("Favorites")
                        .HasForeignKey("MessageCommentId");

                    b.HasOne("planetnineserver.Models.Moon", null)
                        .WithMany("Favorites")
                        .HasForeignKey("MoonId");

                    b.HasOne("planetnineserver.Models.Planet", null)
                        .WithMany("Favorites")
                        .HasForeignKey("PlanetId");

                    b.HasOne("planetnineserver.Models.Post", null)
                        .WithMany("Favorites")
                        .HasForeignKey("PostId");

                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Follower", b =>
                {
                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany("Followers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Message", b =>
                {
                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.MessageComment", b =>
                {
                    b.HasOne("planetnineserver.Models.Message", "Message")
                        .WithMany("MessageComments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Moon", b =>
                {
                    b.HasOne("planetnineserver.Models.Planet", "Planet")
                        .WithMany("Moons")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany("Moons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Planet", b =>
                {
                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany("Planets")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.Post", b =>
                {
                    b.HasOne("planetnineserver.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("planetnineserver.Models.ArtificialIntelligence", b =>
                {
                    b.Navigation("ChatComments");

                    b.Navigation("Chats");
                });

            modelBuilder.Entity("planetnineserver.Models.Chat", b =>
                {
                    b.Navigation("ChatComments");

                    b.Navigation("Comments");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("planetnineserver.Models.ChatComment", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("planetnineserver.Models.Comment", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("planetnineserver.Models.Message", b =>
                {
                    b.Navigation("MessageComments");
                });

            modelBuilder.Entity("planetnineserver.Models.MessageComment", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("planetnineserver.Models.Moon", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("planetnineserver.Models.Planet", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Moons");
                });

            modelBuilder.Entity("planetnineserver.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("planetnineserver.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Followers");

                    b.Navigation("Moons");

                    b.Navigation("Planets");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
